import type {
  Customer,
  Supplier,
  Quotation,
  SalesOrder,
  EngineeringDrawing,
  EngineeringProject,
  EngineeringChange,
  BillOfMaterials,
  BillOfQuantities,
  ProductionWorkOrder,
  Invoice,
  PurchaseOrder,
  Item,
  Location,
  DrawingApproval,
  DrawingComment,
} from "./types"

/* =========================
 *  MASTER DATA
 * =======================*/

export const customers: Customer[] = [
  {
    id: "1",
    name: "Acme Construction Corp",
    contactPerson: "John Smith",
    email: "john.smith@acmeconstruction.com",
    phone: "+1 (555) 123-4567",
    address: "123 Industrial Blvd",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    status: "Active",
    creditLimit: 500000,
    paymentTerms: "Net 30",
    totalOrders: 15,
    engineeringStandards: ["ASTM A992", "AISC 360", "AWS D1.1"],
    qualityRequirements: ["MTRs Required", "NDT Testing", "Weld Qualification"],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    name: "Metro Steel Works",
    contactPerson: "Sarah Johnson",
    email: "sarah.johnson@metrosteel.com",
    phone: "+1 (555) 987-6543",
    address: "456 Manufacturing Ave",
    city: "Detroit",
    state: "MI",
    zipCode: "48201",
    country: "USA",
    status: "Active",
    creditLimit: 750000,
    paymentTerms: "Net 45",
    totalOrders: 8,
    engineeringStandards: ["ASTM A36", "AISC 360", "AWS D1.1"],
    qualityRequirements: ["Standard Quality", "Visual Inspection"],
    createdAt: "2024-02-01T09:15:00Z",
    updatedAt: "2024-02-10T16:45:00Z",
  },
  {
    id: "3",
    name: "Blue Ridge Fabricators",
    contactPerson: "Evelyn Carter",
    email: "evelyn.carter@brfabricators.com",
    phone: "+1 (555) 222-7744",
    address: "77 Foundry Way",
    city: "Charlotte",
    state: "NC",
    zipCode: "28202",
    country: "USA",
    status: "Active",
    creditLimit: 250000,
    paymentTerms: "Net 30",
    totalOrders: 3,
    engineeringStandards: ["ASTM A36", "AISC 360"],
    qualityRequirements: ["Standard Quality"],
    createdAt: "2024-02-05T10:00:00Z",
    updatedAt: "2024-02-15T12:00:00Z",
  },
  {
    id: "4",
    name: "Pacific Bridge & Steel",
    contactPerson: "Michael Chang",
    email: "mchang@pacificbridge.com",
    phone: "+1 (555) 444-1122",
    address: "888 Harbor Drive",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    country: "USA",
    status: "Active",
    creditLimit: 1200000,
    paymentTerms: "Net 60",
    totalOrders: 22,
    engineeringStandards: ["ASTM A709", "AASHTO", "AWS D1.5"],
    qualityRequirements: ["MTRs Required", "NDT Testing", "Weld Qualification", "Fracture Critical"],
    createdAt: "2023-11-15T08:00:00Z",
    updatedAt: "2024-02-18T16:30:00Z",
  },
  {
    id: "5",
    name: "Texas Oilfield Services",
    contactPerson: "Rebecca Martinez",
    email: "rmartinez@texasoil.com",
    phone: "+1 (555) 777-8899",
    address: "555 Rig Road",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    country: "USA",
    status: "Active",
    creditLimit: 800000,
    paymentTerms: "Net 45",
    totalOrders: 12,
    engineeringStandards: ["API 5L", "ASME B31.3", "AWS D1.1"],
    qualityRequirements: ["MTRs Required", "NDT Testing", "Weld Qualification", "Corrosion Resistant"],
    createdAt: "2023-12-01T09:00:00Z",
    updatedAt: "2024-02-20T14:15:00Z",
  },
  {
    id: "6",
    name: "Northeast Power Solutions",
    contactPerson: "David Thompson",
    email: "dthompson@northeastpower.com",
    phone: "+1 (555) 333-6677",
    address: "222 Power Plant Way",
    city: "Boston",
    state: "MA",
    zipCode: "02101",
    country: "USA",
    status: "Active",
    creditLimit: 600000,
    paymentTerms: "Net 30",
    totalOrders: 7,
    engineeringStandards: ["ASME BPVC", "ASTM A516", "AWS D1.1"],
    qualityRequirements: ["MTRs Required", "NDT Testing", "Weld Qualification", "High Temperature"],
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-02-22T11:45:00Z",
  },
  {
    id: "7",
    name: "Midwest Mining Equipment",
    contactPerson: "Jennifer White",
    email: "jwhite@midwestmining.com",
    phone: "+1 (555) 666-4455",
    address: "333 Mine Shaft Lane",
    city: "Minneapolis",
    state: "MN",
    zipCode: "55401",
    country: "USA",
    status: "Inactive",
    creditLimit: 400000,
    paymentTerms: "Net 30",
    totalOrders: 5,
    engineeringStandards: ["ASTM A514", "AISC 360", "AWS D1.1"],
    qualityRequirements: ["MTRs Required", "NDT Testing", "Weld Qualification", "Abrasion Resistant"],
    createdAt: "2023-10-01T08:00:00Z",
    updatedAt: "2024-01-15T16:20:00Z",
  },
  {
    id: "8",
    name: "California Solar Systems",
    contactPerson: "Alex Rodriguez",
    email: "arodriguez@californiasolar.com",
    phone: "+1 (555) 999-2233",
    address: "777 Solar Panel Blvd",
    city: "San Francisco",
    state: "CA",
    zipCode: "94101",
    country: "USA",
    status: "Active",
    creditLimit: 300000,
    paymentTerms: "Net 30",
    totalOrders: 4,
    engineeringStandards: ["ASTM A36", "AISC 360", "AWS D1.1"],
    qualityRequirements: ["Standard Quality", "Weather Resistant Coating"],
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-25T13:30:00Z",
  }
]

export const suppliers: Supplier[] = [
  {
    id: "1",
    name: "Steel Supply Co",
    contactPerson: "Mike Wilson",
    email: "mike.wilson@steelsupply.com",
    phone: "+1 (555) 234-5678",
    address: "789 Steel Mill Rd",
    city: "Pittsburgh",
    state: "PA",
    zipCode: "15201",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 14,
    qualityRating: 4.8,
    rating: 4.8,
    totalOrders: 45,
    specialties: ["Structural Steel", "Steel Beams", "Steel Plates"],
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-25T11:20:00Z",
  },
  {
    id: "2",
    name: "Welding Supply Inc",
    contactPerson: "Priya Nair",
    email: "priya.nair@weldingsupply.com",
    phone: "+1 (555) 333-5588",
    address: "12 Torch Ln",
    city: "Cleveland",
    state: "OH",
    zipCode: "44114",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 5,
    qualityRating: 4.6,
    rating: 4.6,
    totalOrders: 21,
    specialties: ["Welding Rods", "Shielding Gas"],
    createdAt: "2024-01-08T09:30:00Z",
    updatedAt: "2024-01-18T09:30:00Z",
  },
  {
    id: "3",
    name: "Precision Fasteners Ltd",
    contactPerson: "Robert Chen",
    email: "rchen@precisionfasteners.com",
    phone: "+1 (555) 555-1234",
    address: "456 Bolt Street",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46201",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 7,
    qualityRating: 4.9,
    rating: 4.9,
    totalOrders: 38,
    specialties: ["High Strength Bolts", "Nuts", "Washers", "Anchor Bolts"],
    createdAt: "2023-12-01T08:00:00Z",
    updatedAt: "2024-02-15T14:20:00Z",
  },
  {
    id: "4",
    name: "Industrial Coatings Plus",
    contactPerson: "Lisa Anderson",
    email: "landerson@industrialcoatings.com",
    phone: "+1 (555) 777-8888",
    address: "789 Paint Avenue",
    city: "Cincinnati",
    state: "OH",
    zipCode: "45201",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 10,
    qualityRating: 4.7,
    rating: 4.7,
    totalOrders: 29,
    specialties: ["Primers", "Industrial Paints", "Anti-Corrosion Coatings", "Fire Retardant"],
    createdAt: "2023-11-15T09:00:00Z",
    updatedAt: "2024-02-18T16:45:00Z",
  },
  {
    id: "5",
    name: "Quality Steel Processing",
    contactPerson: "James Miller",
    email: "jmiller@qualitysteel.com",
    phone: "+1 (555) 888-9999",
    address: "321 Steel Processing Way",
    city: "Birmingham",
    state: "AL",
    zipCode: "35201",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 45",
    leadTime: 21,
    qualityRating: 4.5,
    rating: 4.5,
    totalOrders: 15,
    specialties: ["Custom Steel Shapes", "Precision Cutting", "Heat Treatment", "Surface Finishing"],
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-02-20T12:30:00Z",
  },
  {
    id: "6",
    name: "Advanced Welding Technologies",
    contactPerson: "Maria Garcia",
    email: "mgarcia@advancedwelding.com",
    phone: "+1 (555) 111-2222",
    address: "654 Welding Drive",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85001",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 12,
    qualityRating: 4.8,
    rating: 4.8,
    totalOrders: 33,
    specialties: ["Welding Equipment", "Welding Consumables", "Welding Training", "Custom Fabrication"],
    createdAt: "2023-10-01T08:00:00Z",
    updatedAt: "2024-02-22T15:15:00Z",
  },
  {
    id: "7",
    name: "Metro Steel",
    contactPerson: "Thomas Brown",
    email: "tbrown@metrosteel.com",
    phone: "+1 (555) 444-5555",
    address: "987 Steel Mill Boulevard",
    city: "Gary",
    state: "IN",
    zipCode: "46401",
    country: "USA",
    status: "Suspended",
    paymentTerms: "Net 30",
    leadTime: 28,
    qualityRating: 3.8,
    rating: 3.8,
    totalOrders: 12,
    specialties: ["Structural Steel", "Steel Plates", "Steel Beams"],
    createdAt: "2023-09-01T09:00:00Z",
    updatedAt: "2024-01-20T10:45:00Z",
    notes: "Quality issues reported, temporarily suspended",
  },
  {
    id: "8",
    name: "Midwest Steel",
    contactPerson: "Patricia Davis",
    email: "pdavis@midweststeel.com",
    phone: "+1 (555) 666-7777",
    address: "456 Industrial Parkway",
    city: "Milwaukee",
    state: "WI",
    zipCode: "53201",
    country: "USA",
    status: "Active",
    paymentTerms: "Net 30",
    leadTime: 18,
    qualityRating: 4.6,
    rating: 4.6,
    totalOrders: 26,
    specialties: ["Steel Plates", "Steel Sheets", "Custom Steel Products", "Steel Processing"],
    createdAt: "2023-12-15T10:00:00Z",
    updatedAt: "2024-02-25T14:20:00Z",
  }
]

/* =========================
 *  ENGINEERING PROJECTS
 * =======================*/

export const engineeringProjects: EngineeringProject[] = [
  {
    id: "PROJ-001",
    projectNumber: "EP-2024-001",
    customerId: "1",
    customerName: "Acme Construction Corp",
    title: "Custom Steel Beam Design",
    description: "Design and engineering of custom I-beam assembly for commercial building",
    status: "Completed",
    priority: "High",
    projectType: "Custom Design",
    estimatedHours: 120,
    actualHours: 135,
    estimatedCost: 15000,
    actualCost: 16875,
    startDate: "2024-01-15",
    dueDate: "2024-02-15",
    completionDate: "2024-02-10",
    assignedEngineer: "Jane Engineer",
    projectManager: "Alice Manager",
    customerRequirements: "Custom I-beam with welded connection plates, ASTM A992 Grade 50 steel",
    technicalSpecifications: "W12x26 section, 20ft length, welded connections, primed finish",
    constraints: ["Must meet AISC 360 seismic requirements", "Delivery within 8 weeks"],
    risks: ["Material availability", "Welding qualification requirements"],
    deliverables: ["Engineering drawings", "BOM", "Fabrication instructions", "Quality plan"],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-02-10T14:00:00Z",
    revision: "Rev B",
    notes: "Project completed ahead of schedule",
  },
  {
    id: "PROJ-002",
    projectNumber: "EP-2024-002",
    customerId: "2",
    customerName: "Metro Steel Works",
    title: "Structural Column Modification",
    description: "Modification of standard W14x30 column for warehouse expansion",
    status: "Under Review",
    priority: "Medium",
    projectType: "Modification",
    estimatedHours: 80,
    actualHours: 0,
    estimatedCost: 10000,
    actualCost: 0,
    startDate: "2024-02-10",
    dueDate: "2024-03-10",
    assignedEngineer: "Marcus Lee",
    projectManager: "Bob Senior",
    customerRequirements: "Modify standard column with additional connection points",
    technicalSpecifications: "W14x30 section, 12ft length, additional bolt holes",
    constraints: ["Must maintain structural integrity", "Use existing column stock"],
    risks: ["Connection design complexity", "Material compatibility"],
    deliverables: ["Modified drawings", "Connection calculations", "Installation guide"],
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-02-12T10:00:00Z",
    revision: "Rev A",
    notes: "Awaiting weld detail confirmation",
  },
]

/* =========================
 *  DRAWING APPROVALS
 * =======================*/

export const drawingApprovals: DrawingApproval[] = [
  {
    id: "APP-001",
    drawingId: "DWG1",
    role: "Lead Engineer",
    approverName: "Jane Engineer",
    approverEmail: "jane.engineer@company.com",
    status: "Approved",
    approvedAt: "2024-01-28T14:00:00Z",
    comments: "Technical review complete. All calculations verified.",
    requiredForRelease: true,
    order: 1,
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-01-28T14:00:00Z",
  },
  {
    id: "APP-002",
    drawingId: "DWG1",
    role: "Production Manager",
    approverName: "Mike Johnson",
    approverEmail: "mike.johnson@company.com",
    status: "Approved",
    approvedAt: "2024-01-29T10:30:00Z",
    comments: "Production feasibility confirmed. Ready for manufacturing.",
    requiredForRelease: true,
    order: 2,
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-01-29T10:30:00Z",
  },
  {
    id: "APP-003",
    drawingId: "DWG1",
    role: "Quality Manager",
    approverName: "Sarah Davis",
    approverEmail: "sarah.davis@company.com",
    status: "Approved",
    approvedAt: "2024-01-30T16:15:00Z",
    comments: "Quality standards compliance verified. Inspection points confirmed.",
    requiredForRelease: true,
    order: 3,
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-01-30T16:15:00Z",
  },
  {
    id: "APP-004",
    drawingId: "DWG2",
    role: "Lead Engineer",
    approverName: "Jane Engineer",
    approverEmail: "jane.engineer@company.com",
    status: "Pending",
    comments: "",
    requiredForRelease: true,
    order: 1,
    createdAt: "2024-02-12T09:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
  },
  {
    id: "APP-005",
    drawingId: "DWG2",
    role: "Production Manager",
    approverName: "Mike Johnson",
    approverEmail: "mike.johnson@company.com",
    status: "Pending",
    comments: "",
    requiredForRelease: true,
    order: 2,
    createdAt: "2024-02-12T09:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
  },
  {
    id: "APP-006",
    drawingId: "DWG2",
    role: "Quality Manager",
    approverName: "Sarah Davis",
    approverEmail: "sarah.davis@company.com",
    status: "Pending",
    comments: "",
    requiredForRelease: true,
    order: 3,
    createdAt: "2024-02-12T09:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
  },
]

/* =========================
 *  DRAWING COMMENTS
 * =======================*/

export const drawingComments: DrawingComment[] = [
  {
    id: "COM-001",
    drawingId: "DWG1",
    authorName: "Mike Johnson",
    authorRole: "Production Manager",
    commentType: "Production Review",
    content: "The beam connection detail in section A-A needs clarification for field welding access.",
    priority: "Medium",
    status: "Resolved",
    relatedApprovalId: "APP-002",
    createdAt: "2024-01-27T10:30:00Z",
    updatedAt: "2024-01-28T14:00:00Z",
    resolvedAt: "2024-01-28T14:00:00Z",
    resolvedBy: "Jane Engineer",
  },
  {
    id: "COM-002",
    drawingId: "DWG1",
    authorName: "Sarah Davis",
    authorRole: "Quality Manager",
    commentType: "Quality Review",
    content: "Please add inspection points for critical welds as per AWS D1.1 requirements.",
    priority: "High",
    status: "Resolved",
    relatedApprovalId: "APP-003",
    createdAt: "2024-01-28T14:15:00Z",
    updatedAt: "2024-01-29T16:00:00Z",
    resolvedAt: "2024-01-29T16:00:00Z",
    resolvedBy: "Jane Engineer",
  },
  {
    id: "COM-003",
    drawingId: "DWG1",
    authorName: "Tom Wilson",
    authorRole: "Fabrication Supervisor",
    commentType: "Technical Review",
    content: "Material list looks good. Confirm delivery schedule with procurement.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2024-01-26T09:45:00Z",
    updatedAt: "2024-01-27T11:00:00Z",
    resolvedAt: "2024-01-27T11:00:00Z",
    resolvedBy: "Mike Johnson",
  },
  {
    id: "COM-004",
    drawingId: "DWG2",
    authorName: "Jane Engineer",
    authorRole: "Lead Engineer",
    commentType: "Technical Review",
    content: "Welding specifications need to be updated to reflect new quality requirements.",
    priority: "High",
    status: "Open",
    relatedApprovalId: "APP-004",
    createdAt: "2024-02-12T11:30:00Z",
    updatedAt: "2024-02-12T11:30:00Z",
  },
]

/* =========================
 *  ENGINEERING CHANGES
 * =======================*/

export const engineeringChanges: EngineeringChange[] = [
  {
    id: "EC-001",
    changeNumber: "EC-2024-001",
    drawingId: "DWG1",
    changeType: "Design",
    priority: "High",
    status: "Implemented",
    reason: "Customer requested additional connection points",
    description: "Added two additional bolt holes for mounting brackets",
    impact: "Increased fabrication time by 2 hours, additional material cost $150",
    costImpact: 150,
    scheduleImpact: 2,
    proposedBy: "John Smith (Customer)",
    reviewedBy: "Jane Engineer",
    approvedBy: "Alice Manager",
    implementationDate: "2024-01-28",
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-01-28T14:00:00Z",
    notes: "Change approved and implemented in Rev B",
  },
  {
    id: "EC-002",
    changeNumber: "EC-2024-002",
    drawingId: "DWG2",
    changeType: "Specification",
    priority: "Medium",
    status: "Under Review",
    reason: "Updated welding specifications",
    description: "Changed from E70XX to E7018 welding rod for improved quality",
    impact: "Minimal cost impact, improved weld quality",
    costImpact: 25,
    scheduleImpact: 0,
    proposedBy: "Marcus Lee",
    reviewedBy: "Bob Senior",
    approvedBy: "",
    createdAt: "2024-02-12T09:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
    notes: "Pending approval from quality department",
  },
]

/* =========================
 *  FRONT-OF-HOUSE DOCS
 * =======================*/

export const quotations: Quotation[] = [
  {
    id: "Q1",
    customerId: "1",
    customerName: "Acme Construction Corp",
    quotationNumber: "Q-2024-001",
    title: "Custom Steel Beams for Building Project",
    description: "Fabrication of custom I-beams for commercial building construction",
    status: "Approved",
    items: [
      {
        id: "Q1-I1",
        description: "W12x26 Steel I-Beam, 20ft length",
        quantity: 10,
        unitPrice: 450.0,
        totalPrice: 4500.0,
        deliveryDate: "2024-03-15",
        specifications: "ASTM A992 Grade 50 steel",
        isNewItem: false,
        engineeringHours: 12,
        engineeringRate: 125.0,
        engineeringCost: 1500.0,
        materialCost: 3800.0,
        laborCost: 1200.0,
        overheadCost: 600.0,
        profitMargin: 900.0,
        bomId: "BOM1",
        drawingId: "DWG1",
      },
      {
        id: "Q1-I2",
        description: "Custom connection plates",
        quantity: 20,
        unitPrice: 75.0,
        totalPrice: 1500.0,
        deliveryDate: "2024-03-15",
        specifications: "1/2 inch thick A36 steel plate",
        isNewItem: true,
        engineeringHours: 8,
        engineeringRate: 125.0,
        engineeringCost: 1000.0,
        materialCost: 800.0,
        laborCost: 400.0,
        overheadCost: 200.0,
        profitMargin: 300.0,
        drawingId: "DWG1",
      },
    ],
    subtotal: 6000.0,
    engineeringCost: 2500.0,
    materialCost: 4600.0,
    laborCost: 1600.0,
    overheadCost: 800.0,
    profitMargin: 1200.0,
    tax: 480.0, // 8%
    total: 6480.0,
    validUntil: "2024-03-01",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-25T14:30:00Z",
    revision: "Rev A",
    engineeringProjectId: "PROJ-001",
    salesPerson: "Mike Sales",
    engineeringReviewer: "Jane Engineer",
    managementApprover: "Alice Manager",
    customerRequirements: "Custom I-beam assembly with connection plates for commercial building",
    // ETO Workflow fields
    workflowStage: "PO Received",
    assignedEngineer: "Jane Engineer",
    estimatedEngineeringHours: 40,
    engineeringStatus: "Approved",
    drawingRevision: "Rev A",
    drawingNotes: "Final approved drawings for customer review",
    engineeringDrawingCreated: true,
    boqGenerated: true,
    boqId: "BOQ-001",
    sentToCustomer: true,
    customerFeedbackReceived: true,
    poReceived: true,
    convertedToSO: false,
    technicalSpecifications: "ASTM A992 Grade 50 steel, welded connections, primed finish",
    deliveryTerms: "FOB Factory, 8 weeks from order confirmation",
    paymentTerms: "Net 30",
    warrantyTerms: "1 year warranty on materials and workmanship",
    notes: "Customer requested expedited delivery",
    changeHistory: [],
  },
  {
    id: "Q2",
    customerId: "2",
    customerName: "Metro Steel Works",
    quotationNumber: "Q-2024-002",
    title: "Structural Steel Columns",
    description: "W14x30 steel columns for warehouse expansion",
    status: "Customer Review",
    items: [
      {
        id: "Q2-I1",
        description: "W14x30 Steel Column, 12ft length",
        quantity: 8,
        unitPrice: 520.0,
        totalPrice: 4160.0,
        deliveryDate: "2024-04-01",
        specifications: "ASTM A992 Grade 50 steel",
        isNewItem: false,
        engineeringHours: 6,
        engineeringRate: 125.0,
        engineeringCost: 750.0,
        materialCost: 3360.0,
        laborCost: 800.0,
        overheadCost: 400.0,
        profitMargin: 600.0,
        bomId: "BOM2",
        drawingId: "DWG2",
      },
    ],
    subtotal: 4160.0,
    engineeringCost: 750.0,
    materialCost: 3360.0,
    laborCost: 800.0,
    overheadCost: 400.0,
    profitMargin: 600.0,
    tax: 332.8,
    total: 4492.8,
    validUntil: "2024-03-10",
    createdAt: "2024-02-08T11:00:00Z",
    updatedAt: "2024-02-09T09:00:00Z",
    revision: "Rev A",
    engineeringProjectId: "PROJ-002",
    salesPerson: "Mike Sales",
    engineeringReviewer: "Marcus Lee",
    managementApprover: "",
    customerRequirements: "Modified W14x30 columns with additional connection points",
    technicalSpecifications: "ASTM A992 Grade 50 steel, modified for warehouse expansion",
    deliveryTerms: "FOB Factory, 6 weeks from order confirmation",
    paymentTerms: "Net 45",
    warrantyTerms: "1 year warranty on materials and workmanship",
    notes: "Pending customer review of modifications",
    changeHistory: [],
  },
  {
    id: "Q3",
    customerId: "3",
    customerName: "Blue Ridge Fabricators",
    quotationNumber: "Q-2024-003",
    title: "Stair Stringers & Brackets",
    description: "Fabrication of stair stringers with mounting brackets",
    status: "Under Review",
    items: [
      {
        id: "Q3-I1",
        description: "Stair Stringer Assembly",
        quantity: 6,
        unitPrice: 300.0,
        totalPrice: 1800.0,
        deliveryDate: "2024-03-25",
        specifications: "A36 steel, primed",
        isNewItem: false,
        engineeringHours: 4,
        engineeringRate: 125.0,
        engineeringCost: 500.0,
        materialCost: 1200.0,
        laborCost: 600.0,
        overheadCost: 300.0,
        profitMargin: 450.0,
      },
      {
        id: "Q3-I2",
        description: "Mounting Brackets",
        quantity: 12,
        unitPrice: 30.0,
        totalPrice: 360.0,
        deliveryDate: "2024-03-25",
        specifications: "A36 steel 1/4 inch",
        isNewItem: true,
        engineeringHours: 2,
        engineeringRate: 125.0,
        engineeringCost: 250.0,
        materialCost: 180.0,
        laborCost: 120.0,
        overheadCost: 60.0,
        profitMargin: 90.0,
      },
    ],
    subtotal: 2160.0,
    engineeringCost: 750.0,
    materialCost: 1380.0,
    laborCost: 720.0,
    overheadCost: 360.0,
    profitMargin: 540.0,
    tax: 172.8,
    total: 2332.8,
    validUntil: "2024-03-05",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-02-16T10:00:00Z",
    revision: "Rev A",
    salesPerson: "Mike Sales",
    engineeringReviewer: "",
    managementApprover: "",
    customerRequirements: "Standard stair stringers with mounting brackets",
    technicalSpecifications: "A36 steel, primed finish, standard dimensions",
    deliveryTerms: "FOB Factory, 4 weeks from order confirmation",
    paymentTerms: "Net 30",
    warrantyTerms: "1 year warranty on materials and workmanship",
    notes: "Standard design, minimal engineering required",
    changeHistory: [],
  },
  {
    id: "Q4",
    customerId: "4",
    customerName: "Pacific Bridge & Steel",
    quotationNumber: "Q-2024-004",
    title: "Bridge Girder Fabrication",
    description: "Fabrication of custom bridge girders for highway expansion project",
    status: "Sent",
    items: [
      {
        id: "Q4-I1",
        description: "Plate Girder Assembly - 80ft span",
        quantity: 4,
        unitPrice: 8500.0,
        totalPrice: 34000.0,
        deliveryDate: "2024-06-15",
        specifications: "ASTM A709 Grade 50 steel, fracture critical",
        isNewItem: true,
        engineeringHours: 80,
        engineeringRate: 125.0,
        engineeringCost: 10000.0,
        materialCost: 25000.0,
        laborCost: 12000.0,
        overheadCost: 6000.0,
        profitMargin: 8000.0,
      },
      {
        id: "Q4-I2",
        description: "Connection details and stiffeners",
        quantity: 16,
        unitPrice: 450.0,
        totalPrice: 7200.0,
        deliveryDate: "2024-06-15",
        specifications: "ASTM A709 Grade 50 steel",
        isNewItem: true,
        engineeringHours: 20,
        engineeringRate: 125.0,
        engineeringCost: 2500.0,
        materialCost: 4000.0,
        laborCost: 2000.0,
        overheadCost: 1000.0,
        profitMargin: 1500.0,
      },
    ],
    subtotal: 41200.0,
    engineeringCost: 12500.0,
    materialCost: 29000.0,
    laborCost: 14000.0,
    overheadCost: 7000.0,
    profitMargin: 9500.0,
    tax: 3296.0,
    total: 44496.0,
    validUntil: "2024-04-15",
    createdAt: "2024-02-20T14:00:00Z",
    updatedAt: "2024-02-22T16:30:00Z",
    revision: "Rev A",
    salesPerson: "Sarah Johnson",
    engineeringReviewer: "Jane Engineer",
    managementApprover: "Alice Manager",
    customerRequirements: "Fracture critical bridge girders meeting AASHTO specifications",
    technicalSpecifications: "ASTM A709 Grade 50 steel, fracture critical design, NDT testing required",
    deliveryTerms: "FOB Factory, 16 weeks from order confirmation",
    paymentTerms: "Net 60",
    warrantyTerms: "5 year warranty on materials and workmanship",
    notes: "Major infrastructure project, requires DOT approval",
    changeHistory: [],
  },
  {
    id: "Q5",
    customerId: "5",
    customerName: "Texas Oilfield Services",
    quotationNumber: "Q-2024-005",
    title: "Pressure Vessel Components",
    description: "Fabrication of pressure vessel components for oilfield processing",
    status: "Under Review",
    items: [
      {
        id: "Q5-I1",
        description: "Pressure Vessel Shell - 48\" diameter x 20ft",
        quantity: 2,
        unitPrice: 12000.0,
        totalPrice: 24000.0,
        deliveryDate: "2024-05-20",
        specifications: "API 5L Grade X52, ASME B31.3",
        isNewItem: true,
        engineeringHours: 60,
        engineeringRate: 125.0,
        engineeringCost: 7500.0,
        materialCost: 18000.0,
        laborCost: 9000.0,
        overheadCost: 4500.0,
        profitMargin: 6000.0,
      },
      {
        id: "Q5-I2",
        description: "End caps and flanges",
        quantity: 4,
        unitPrice: 1800.0,
        totalPrice: 7200.0,
        deliveryDate: "2024-05-20",
        specifications: "API 5L Grade X52, ASME B16.5",
        isNewItem: false,
        engineeringHours: 15,
        engineeringRate: 125.0,
        engineeringCost: 1875.0,
        materialCost: 5000.0,
        laborCost: 2500.0,
        overheadCost: 1250.0,
        profitMargin: 1875.0,
      },
    ],
    subtotal: 31200.0,
    engineeringCost: 9375.0,
    materialCost: 23000.0,
    laborCost: 11500.0,
    overheadCost: 5750.0,
    profitMargin: 7875.0,
    tax: 2496.0,
    total: 33696.0,
    validUntil: "2024-04-20",
    createdAt: "2024-02-25T11:00:00Z",
    updatedAt: "2024-02-26T15:45:00Z",
    revision: "Rev A",
    salesPerson: "Sarah Johnson",
    engineeringReviewer: "Marcus Lee",
    managementApprover: "",
    customerRequirements: "ASME code pressure vessel components for oilfield processing",
    technicalSpecifications: "API 5L Grade X52 steel, ASME B31.3 design, corrosion resistant coating",
    deliveryTerms: "FOB Factory, 12 weeks from order confirmation",
    paymentTerms: "Net 45",
    warrantyTerms: "2 year warranty on materials and workmanship",
    notes: "Requires ASME code stamp and third-party inspection",
    changeHistory: [],
  },
  {
    id: "Q6",
    customerId: "6",
    customerName: "Northeast Power Solutions",
    quotationNumber: "Q-2024-006",
    title: "Boiler Support Structure",
    description: "Fabrication of structural support for power plant boiler",
    status: "Draft",
    items: [
      {
        id: "Q6-I1",
        description: "Boiler Support Beams - W18x60",
        quantity: 12,
        unitPrice: 2800.0,
        totalPrice: 33600.0,
        deliveryDate: "2024-07-01",
        specifications: "ASTM A516 Grade 70, high temperature service",
        isNewItem: false,
        engineeringHours: 25,
        engineeringRate: 125.0,
        engineeringCost: 3125.0,
        materialCost: 28000.0,
        laborCost: 14000.0,
        overheadCost: 7000.0,
        profitMargin: 7000.0,
      },
      {
        id: "Q6-I2",
        description: "Support columns and bracing",
        quantity: 8,
        unitPrice: 1200.0,
        totalPrice: 9600.0,
        deliveryDate: "2024-07-01",
        specifications: "ASTM A516 Grade 70",
        isNewItem: false,
        engineeringHours: 10,
        engineeringRate: 125.0,
        engineeringCost: 1250.0,
        materialCost: 8000.0,
        laborCost: 4000.0,
        overheadCost: 2000.0,
        profitMargin: 2000.0,
      },
    ],
    subtotal: 43200.0,
    engineeringCost: 4375.0,
    materialCost: 36000.0,
    laborCost: 18000.0,
    overheadCost: 9000.0,
    profitMargin: 9000.0,
    tax: 3456.0,
    total: 46656.0,
    validUntil: "2024-05-01",
    createdAt: "2024-02-28T09:00:00Z",
    updatedAt: "2024-02-28T09:00:00Z",
    revision: "Rev A",
    salesPerson: "Mike Sales",
    engineeringReviewer: "",
    managementApprover: "",
    customerRequirements: "High temperature structural support for power plant boiler",
    technicalSpecifications: "ASTM A516 Grade 70 steel, high temperature service, ASME BPVC design",
    deliveryTerms: "FOB Factory, 18 weeks from order confirmation",
    paymentTerms: "Net 30",
    warrantyTerms: "3 year warranty on materials and workmanship",
    notes: "Power plant critical infrastructure project",
    changeHistory: [],
  }
]

export const salesOrders: SalesOrder[] = [
  {
    id: "SO1",
    customerId: "1",
    customerName: "Acme Construction Corp",
    quotationId: "Q1",
    salesOrderNumber: "SO-2024-001",
    customerPO: "PO-ACM-2024-0156",
    title: "Custom Steel Beams for Building Project",
    description: "Fabrication of custom I-beams for commercial building construction",
    status: "In Production",
    items: [
      {
        id: "SO1-I1",
        description: "W12x26 Steel I-Beam, 20ft length",
        quantity: 10,
        unitPrice: 450.0,
        totalPrice: 4500.0,
        deliveryDate: "2024-03-15",
        specifications: "ASTM A992 Grade 50 steel",
        status: "In Production",
        bomId: "BOM1",
        workOrderId: "WO1",
      },
      {
        id: "SO1-I2",
        description: "Custom connection plates",
        quantity: 20,
        unitPrice: 75.0,
        totalPrice: 1500.0,
        deliveryDate: "2024-03-15",
        specifications: "1/2 inch thick A36 steel plate",
        status: "Ready",
      },
    ],
    subtotal: 6000.0,
    tax: 480.0,
    total: 6480.0,
    orderDate: "2024-02-01",
    requestedDeliveryDate: "2024-03-15",
    confirmedDeliveryDate: "2024-03-15",
    shippingAddress: "123 Industrial Blvd, Chicago, IL 60601",
    billingAddress: "123 Industrial Blvd, Chicago, IL 60601",
    paymentTerms: "Net 30",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-15T16:30:00Z",
    revision: "Rev B",
    notes: "Engineering approved Rev B for production",
  },
  {
    id: "SO2",
    customerId: "2",
    customerName: "Metro Steel Works",
    quotationId: "Q2",
    salesOrderNumber: "SO-2024-002",
    customerPO: "PO-MSW-2024-0089",
    title: "Structural Steel Components",
    description: "Various structural steel components for warehouse expansion",
    status: "Confirmed",
    items: [
      {
        id: "SO2-I1",
        description: "W14x30 Steel Column, 12ft length",
        quantity: 8,
        unitPrice: 520.0,
        totalPrice: 4160.0,
        deliveryDate: "2024-04-01",
        specifications: "ASTM A992 Grade 50 steel",
        status: "In Production",
        bomId: "BOM2",
        workOrderId: "WO2",
      },
    ],
    subtotal: 4160.0,
    tax: 332.8,
    total: 4492.8,
    orderDate: "2024-02-10",
    requestedDeliveryDate: "2024-04-01",
    shippingAddress: "456 Manufacturing Ave, Detroit, MI 48201",
    billingAddress: "456 Manufacturing Ave, Detroit, MI 48201",
    paymentTerms: "Net 45",
    createdAt: "2024-02-10T11:00:00Z",
    updatedAt: "2024-02-12T09:15:00Z",
    revision: "Rev A",
    notes: "Awaiting engineering review",
  },
  {
    id: "SO3",
    customerId: "3",
    customerName: "Blue Ridge Fabricators",
    quotationId: "Q3",
    salesOrderNumber: "SO-2024-003",
    customerPO: "PO-BRF-2024-0018",
    title: "Stair Stringers & Brackets",
    description: "Fabrication of stair stringers with mounting brackets",
    status: "Confirmed",
    items: [
      {
        id: "SO3-I1",
        description: "Stair Stringer Assembly",
        quantity: 6,
        unitPrice: 300.0,
        totalPrice: 1800.0,
        deliveryDate: "2024-03-25",
        specifications: "A36 steel, primed",
        status: "Pending",
      },
      {
        id: "SO3-I2",
        description: "Mounting Brackets",
        quantity: 12,
        unitPrice: 30.0,
        totalPrice: 360.0,
        deliveryDate: "2024-03-25",
        specifications: "A36 steel 1/4 inch",
        status: "Pending",
      },
    ],
    subtotal: 2160.0,
    tax: 172.8,
    total: 2332.8,
    orderDate: "2024-02-20",
    requestedDeliveryDate: "2024-03-25",
    shippingAddress: "77 Foundry Way, Charlotte, NC 28202",
    billingAddress: "77 Foundry Way, Charlotte, NC 28202",
    paymentTerms: "Net 30",
    createdAt: "2024-02-20T13:00:00Z",
    updatedAt: "2024-02-21T09:00:00Z",
    revision: "Rev A",
    notes: "Standard lead time",
  },
  {
    id: "SO4",
    customerId: "4",
    customerName: "Pacific Bridge & Steel",
    quotationId: "Q4",
    salesOrderNumber: "SO-2024-004",
    customerPO: "PO-PBS-2024-0034",
    title: "Bridge Girder Fabrication",
    description: "Fabrication of custom bridge girders for highway expansion project",
    status: "Confirmed",
    items: [
      {
        id: "SO4-I1",
        description: "Plate Girder Assembly - 80ft span",
        quantity: 4,
        unitPrice: 8500.0,
        totalPrice: 34000.0,
        deliveryDate: "2024-06-15",
        specifications: "ASTM A709 Grade 50 steel, fracture critical",
        status: "Pending",
      },
      {
        id: "SO4-I2",
        description: "Connection details and stiffeners",
        quantity: 16,
        unitPrice: 450.0,
        totalPrice: 7200.0,
        deliveryDate: "2024-06-15",
        specifications: "ASTM A709 Grade 50 steel",
        status: "Pending",
      },
    ],
    subtotal: 41200.0,
    tax: 3296.0,
    total: 44496.0,
    orderDate: "2024-03-01",
    requestedDeliveryDate: "2024-06-15",
    shippingAddress: "888 Harbor Drive, Seattle, WA 98101",
    billingAddress: "888 Harbor Drive, Seattle, WA 98101",
    paymentTerms: "Net 60",
    createdAt: "2024-03-01T14:00:00Z",
    updatedAt: "2024-03-01T14:00:00Z",
    revision: "Rev A",
    notes: "Major infrastructure project, DOT approval required",
  },
  {
    id: "SO5",
    customerId: "8",
    customerName: "California Solar Systems",
    quotationId: "",
    salesOrderNumber: "SO-2024-005",
    customerPO: "PO-CSS-2024-0022",
    title: "Solar Panel Mounting Structures",
    description: "Fabrication of steel mounting structures for solar panel installation",
    status: "Draft",
    items: [
      {
        id: "SO5-I1",
        description: "Solar Panel Mounting Frame",
        quantity: 50,
        unitPrice: 120.0,
        totalPrice: 6000.0,
        deliveryDate: "2024-04-15",
        specifications: "A36 steel, galvanized finish",
        status: "Pending",
      },
      {
        id: "SO5-I2",
        description: "Ground Mounting Posts",
        quantity: 100,
        unitPrice: 45.0,
        totalPrice: 4500.0,
        deliveryDate: "2024-04-15",
        specifications: "A36 steel, 4\" square tube, galvanized",
        status: "Pending",
      },
    ],
    subtotal: 10500.0,
    tax: 840.0,
    total: 11340.0,
    orderDate: "2024-03-05",
    requestedDeliveryDate: "2024-04-15",
    shippingAddress: "777 Solar Panel Blvd, San Francisco, CA 94101",
    billingAddress: "777 Solar Panel Blvd, San Francisco, CA 94101",
    paymentTerms: "Net 30",
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-05T10:00:00Z",
    revision: "Rev A",
    notes: "Standard solar mounting system",
  }
]

/* =========================
 *  ENGINEERING
 * =======================*/

export const engineeringDrawings: EngineeringDrawing[] = [
  {
    id: "DWG1",
    projectId: "PROJ-001",
    projectNumber: "EP-2024-001",
    drawingNumber: "DWG-2024-001",
    title: "W12x26 I-Beam Assembly",
    description: "Detailed drawing for custom I-beam fabrication",
    status: "Released",
    version: "1.0",
    drawnBy: "Jane Engineer",
    checkedBy: "Bob Senior",
    approvedBy: "Alice Manager",
    createdAt: "2024-01-25T08:00:00Z",
    updatedAt: "2024-02-01T14:00:00Z",
    revision: "Rev B",
    fileUrl: "/drawings/DWG-2024-001.pdf",
    specifications: "ASTM A992 Grade 50 steel, welded connections",
    materials: ["A992 Grade 50 Steel", "E70XX Welding Rod"],
    dimensions: { length: 240, width: 12, height: 12.22, weight: 520 },
    tolerances: "±1/8\" on all dimensions",
    surfaceFinish: "Primed finish",
    weldingSpecs: "E70XX welding rod, AWS D1.1 standards",
    qualityStandards: ["ASTM A992", "AISC 360", "AWS D1.1"],
    inspectionPoints: ["Weld quality", "Dimensions", "Surface finish"],
    notes: "Updated for production release",
    changeHistory: [engineeringChanges[0]],
    // Approval workflow
    approvals: drawingApprovals.filter(a => a.drawingId === "DWG1"),
    comments: drawingComments.filter(c => c.drawingId === "DWG1"),
    submittedForApprovalAt: "2024-01-25T10:00:00Z",
    submittedBy: "Jane Engineer",
    approvalWorkflowStage: "Approved",
    finalApprovalAt: "2024-01-30T16:15:00Z",
    finalApprovalBy: "Sarah Davis",
  },
  {
    id: "DWG2",
    projectId: "PROJ-002",
    projectNumber: "EP-2024-002",
    drawingNumber: "DWG-2024-002",
    title: "W14x30 Column",
    description: "Column fabrication drawing",
    status: "Under Review",
    version: "0.9",
    drawnBy: "Marcus Lee",
    checkedBy: "Bob Senior",
    approvedBy: "—",
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-02-12T10:00:00Z",
    revision: "Rev A",
    fileUrl: "/drawings/DWG-2024-002.pdf",
    specifications: "ASTM A992 Grade 50 steel",
    materials: ["A992 Grade 50 Steel"],
    dimensions: { length: 144, width: 14, height: 13.0, weight: 600 },
    tolerances: "±1/16\" on critical dimensions",
    surfaceFinish: "As-rolled finish",
    weldingSpecs: "E7018 welding rod, AWS D1.1 standards",
    qualityStandards: ["ASTM A992", "AISC 360"],
    inspectionPoints: ["Dimensions", "Material verification"],
    notes: "Awaiting weld detail confirmation",
    changeHistory: [engineeringChanges[1]],
    // Approval workflow
    approvals: drawingApprovals.filter(a => a.drawingId === "DWG2"),
    comments: drawingComments.filter(c => c.drawingId === "DWG2"),
    submittedForApprovalAt: "2024-02-12T09:00:00Z",
    submittedBy: "Marcus Lee",
    approvalWorkflowStage: "Under Review",
  },
]

// Alias often used in UIs
export const engineeringDrawingsAlias = engineeringDrawings

/* =========================
 *  BOM
 * =======================*/

export const billsOfMaterials: BillOfMaterials[] = [
  {
    id: "1",
    bomNumber: "BOM-2024-001",
    productName: "Steel Frame Assembly for Warehouse",
    version: "1.0",
    revision: "A",
    status: "Approved",
    bomType: "EBOM",
    createdBy: "John Smith",
    engineeringProjectId: "1",
    engineeringDrawingId: "1",
    boqId: "1",
    items: [
      {
        id: "BOM-2024-001-I1",
        itemNumber: "1.0",
        description: "W12x65 Steel I-Beam",
        partNumber: "STL-W12x65",
        quantity: 8,
        unit: "EA",
        unitCost: 2450,
        totalCost: 19600,
        materialGrade: "A992",
        specifications: "ASTM A992/A992M Grade 50, 20ft length",
        supplier: "Steel Supply Co.",
        leadTime: 14,
        category: "Structural Steel",
        boqItemId: "1.1"
      },
      {
        id: "BOM-2024-001-I2",
        itemNumber: "2.0",
        description: "W8x31 Steel Column",
        partNumber: "STL-W8x31",
        quantity: 12,
        unit: "EA",
        unitCost: 1280,
        totalCost: 15360,
        materialGrade: "A992",
        specifications: "ASTM A992/A992M Grade 50, 16ft length",
        supplier: "Metro Steel",
        leadTime: 21,
        category: "Structural Steel",
        boqItemId: "1.2"
      },
      {
        id: "BOM-2024-001-I3",
        itemNumber: "3.0",
        description: "Steel Angle L4x4x1/2",
        partNumber: "STL-L4x4x0.5",
        quantity: 50,
        unit: "EA",
        unitCost: 85,
        totalCost: 4250,
        materialGrade: "A36",
        specifications: "ASTM A36/A36M, 8ft length",
        supplier: "Steel Supply Co.",
        leadTime: 7,
        category: "Structural Steel",
        boqItemId: "1.3"
      },
      {
        id: "BOM-2024-001-I4",
        itemNumber: "4.0",
        description: "Steel Plate 1/2\" x 12\" x 20\"",
        partNumber: "STL-PLT-0.5x12x20",
        quantity: 25,
        unit: "EA",
        unitCost: 150,
        totalCost: 3750,
        materialGrade: "A36",
        specifications: "ASTM A36/A36M hot rolled steel plate",
        supplier: "Midwest Steel",
        leadTime: 14,
        category: "Steel Plate",
        boqItemId: "1.4"
      },
      {
        id: "BOM-2024-001-I5",
        itemNumber: "5.0",
        description: "High Strength Bolts 3/4\" x 6\"",
        partNumber: "BOLT-A325-0.75x6",
        quantity: 200,
        unit: "EA",
        unitCost: 12,
        totalCost: 2400,
        materialGrade: "A325",
        specifications: "ASTM A325 Type 1, hex head with nut and washer",
        supplier: "Fastener World",
        leadTime: 7,
        category: "Hardware",
        boqItemId: "1.5"
      }
    ],
    totalCost: 45360,
    itemCount: 5,
    notes: "Primary structural BOM for warehouse frame assembly. All materials meet AISC specifications.",
    createdAt: "2024-01-12T09:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z"
  },
  {
    id: "2",
    bomNumber: "BOM-2024-002",
    productName: "Piping System Assembly",
    version: "1.0",
    revision: "A",
    status: "Draft",
    bomType: "MBOM",
    createdBy: "Sarah Johnson",
    engineeringProjectId: "2",
    boqId: "2",
    items: [
      {
        id: "BOM-2024-002-I1",
        itemNumber: "1.0",
        description: "6\" CS Pipe ASTM A106",
        partNumber: "PIPE-CS-6-A106",
        quantity: 220,
        unit: "FT",
        unitCost: 45,
        totalCost: 9900,
        materialGrade: "A106 Grade B",
        specifications: "ASTM A106 Grade B seamless carbon steel pipe",
        supplier: "Industrial Piping Supply",
        leadTime: 14,
        category: "Piping",
        boqItemId: "2.1"
      },
      {
        id: "BOM-2024-002-I2",
        itemNumber: "2.0",
        description: "6\" 90° Elbow",
        partNumber: "ELBOW-CS-6-90",
        quantity: 24,
        unit: "EA",
        unitCost: 125,
        totalCost: 3000,
        materialGrade: "A234 WPB",
        specifications: "ASTM A234 WPB butt weld 90° elbow",
        supplier: "Industrial Piping Supply",
        leadTime: 10,
        category: "Pipe Fittings",
        boqItemId: "2.2"
      },
      {
        id: "BOM-2024-002-I3",
        itemNumber: "3.0",
        description: "6\" ANSI B16.5 Flange",
        partNumber: "FLANGE-CS-6-B16.5",
        quantity: 16,
        unit: "EA",
        unitCost: 180,
        totalCost: 2880,
        materialGrade: "A105",
        specifications: "ASTM A105 weld neck flange, 150# rating",
        supplier: "Flange & Fitting Co.",
        leadTime: 7,
        category: "Pipe Fittings",
        boqItemId: "2.3"
      }
    ],
    totalCost: 15780,
    itemCount: 3,
    notes: "Manufacturing BOM for piping system fabrication and installation.",
    createdAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z"
  }
]


/* =========================
 *  BILL OF QUANTITIES
 * =======================*/

export const billsOfQuantities: BillOfQuantities[] = [
  {
    id: "BOQ1",
    boqNumber: "BOQ-2024-001",
    title: "Steel Bridge Fabrication Project",
    projectName: "Highway Bridge Expansion",
    description: "Complete BOQ for custom steel bridge fabrication project",
    status: "Approved",
    version: "1.0",
    items: [
      {
        id: "BOQ1-I1",
        itemNumber: "1.1",
        description: "Supply and installation of structural steel beams - 20 MT",
        quantity: 10,
        unit: "EA",
        unitRate: 125.0,
        totalAmount: 1250.0,
        category: "Labor",
        specifications: "Cut to 20ft length with end prep",
        remarks: "Include beveling for welding",
        workPackage: "Structural Steel Installation",
        engineeringStatus: "Design Complete",
        designComplexity: "Medium",
        requiredDrawings: ["DWG1", "DWG-DETAIL-001"],
      },
      {
        id: "BOQ1-I2",
        itemNumber: "1.2",
        description: "W12x26 Steel I-Beam raw material",
        quantity: 10,
        unit: "EA",
        unitRate: 450.0,
        totalAmount: 4500.0,
        category: "Material",
        specifications: "ASTM A992 Grade 50",
        remarks: "20ft length",
        bomItemId: "BOM1-I1",
      },
      {
        id: "BOQ1-I3",
        itemNumber: "1.3",
        description: "Connection plates fabrication",
        quantity: 20,
        unit: "EA",
        unitRate: 35.0,
        totalAmount: 700.0,
        category: "Labor",
        specifications: "Cut, drill, and finish",
        remarks: "Various sizes as per drawings",
      },
      {
        id: "BOQ1-I4",
        itemNumber: "1.4",
        description: "Steel plate material",
        quantity: 200,
        unit: "LB",
        unitRate: 1.25,
        totalAmount: 250.0,
        category: "Material",
        specifications: "1/2\" thick ASTM A36",
        remarks: "For connection plates",
        bomItemId: "BOM1-I2",
      },
      {
        id: "BOQ1-I5",
        itemNumber: "1.5",
        description: "Welding services",
        quantity: 40,
        unit: "LF",
        unitRate: 15.0,
        totalAmount: 600.0,
        category: "Labor",
        specifications: "FCAW welding per AWS D1.1",
        remarks: "Includes inspection",
      },
      {
        id: "BOQ1-I6",
        itemNumber: "1.6",
        description: "Crane services for assembly",
        quantity: 2,
        unit: "DAY",
        unitRate: 800.0,
        totalAmount: 1600.0,
        category: "Equipment",
        specifications: "50-ton mobile crane",
        remarks: "Including operator",
      },
      {
        id: "BOQ1-I7",
        itemNumber: "1.7",
        description: "Supply and installation of piping system - 200m of 6-inch CS pipe",
        quantity: 1,
        unit: "LOT",
        unitRate: 2500.0,
        totalAmount: 2500.0,
        category: "Subcontract",
        specifications: "Including fittings and supports as per P&ID",
        remarks: "Requires detailed routing design",
        workPackage: "Piping Installation",
        engineeringStatus: "Pending",
        designComplexity: "High",
        requiredDrawings: ["P&ID-001", "ISO-PIPING-001"],
      },
    ],
    materialCost: 4750.0,
    laborCost: 2550.0,
    equipmentCost: 1600.0,
    subcontractCost: 2500.0,
    otherCost: 0.0,
    totalCost: 11400.0,
    createdBy: "Sarah Wilson",
    approvedBy: "Marcus Lee",
    createdAt: "2024-02-10T09:00:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
    revision: "Rev A",
    engineeringProjectId: "EP1",
    engineeringDrawingId: "DWG1",
    bomId: "BOM1",
    notes: "Includes all direct costs for fabrication",
    etoStatus: "Engineering Design",
    engineeringProgress: 75,
    generatedBOMs: ["BOM1"],
    contractReference: "CONTRACT-2024-001",
    workPackages: ["Structural Steel Installation", "Piping Installation"],
  },
  {
    id: "BOQ2",
    boqNumber: "BOQ-2024-002",
    title: "Column Fabrication Estimate",
    projectName: "Industrial Building Columns",
    description: "BOQ for W14x30 column fabrication",
    status: "Draft",
    version: "0.9",
    items: [
      {
        id: "BOQ2-I1",
        itemNumber: "2.1",
        description: "W14x30 Steel Column material",
        quantity: 8,
        unit: "EA",
        unitRate: 420.0,
        totalAmount: 3360.0,
        category: "Material",
        specifications: "ASTM A992, 12ft length",
        remarks: "Raw material cost",
        bomItemId: "BOM2-I1",
      },
      {
        id: "BOQ2-I2",
        itemNumber: "2.2",
        description: "Column cutting and preparation",
        quantity: 8,
        unit: "EA",
        unitRate: 85.0,
        totalAmount: 680.0,
        category: "Labor",
        specifications: "Cut to length and prep ends",
        remarks: "Machine shop work",
      },
      {
        id: "BOQ2-I3",
        itemNumber: "2.3",
        description: "Quality inspection",
        quantity: 1,
        unit: "LOT",
        unitRate: 450.0,
        totalAmount: 450.0,
        category: "Other",
        specifications: "Dimensional inspection",
        remarks: "Third party inspection",
      },
    ],
    materialCost: 3360.0,
    laborCost: 680.0,
    equipmentCost: 0.0,
    subcontractCost: 0.0,
    otherCost: 450.0,
    totalCost: 4490.0,
    createdBy: "Emily Chen",
    createdAt: "2024-02-12T11:00:00Z",
    updatedAt: "2024-02-14T16:30:00Z",
    revision: "Rev A",
    engineeringProjectId: "EP2",
    engineeringDrawingId: "DWG2",
    bomId: "BOM2",
    notes: "Pending customer approval",
    etoStatus: "BOQ Submitted",
    engineeringProgress: 25,
    generatedBOMs: [],
    contractReference: "CONTRACT-2024-002",
    workPackages: ["Column Fabrication"],
  },
]

/* =========================
 *  PRODUCTION
 * =======================*/

export const productionOrders: ProductionWorkOrder[] = [
  {
    id: "WO1",
    workOrderNumber: "WO-2024-001",
    salesOrderId: "SO1",
    bomId: "BOM1",
    productName: "W12x26 Steel I-Beam Assembly",
    description: "Fabricate 10 custom I-beams per specifications",
    quantity: 10,
    status: "In Progress",
    priority: "High",
    startDate: "2024-02-05",
    dueDate: "2024-03-10",
    assignedTo: "Production Team A",
    progress: 65,
    estimatedHours: 80,
    actualHours: 52,
    createdAt: "2024-02-02T08:00:00Z",
    updatedAt: "2024-02-15T16:00:00Z",
    revision: "Rev B",
    notes: "On schedule, quality checks passed",
  },
  {
    id: "WO2",
    workOrderNumber: "WO-2024-002",
    salesOrderId: "SO2",
    bomId: "BOM2",
    productName: "W14x30 Column",
    description: "Cut, drill, and prep columns",
    quantity: 8,
    status: "Planned",
    priority: "Medium",
    startDate: "2024-02-20",
    dueDate: "2024-03-25",
    assignedTo: "Production Team B",
    progress: 10,
    estimatedHours: 50,
    actualHours: 0,
    createdAt: "2024-02-18T08:00:00Z",
    updatedAt: "2024-02-18T08:00:00Z",
    revision: "Rev A",
    notes: "Waiting for final weld details",
  },
  {
    id: "WO3",
    workOrderNumber: "WO-2024-003",
    salesOrderId: "SO3",
    bomId: "",
    productName: "Stair Stringer Assembly",
    description: "Fabricate stair stringers and mounting brackets",
    quantity: 6,
    status: "Planned",
    priority: "Low",
    startDate: "2024-03-01",
    dueDate: "2024-03-20",
    assignedTo: "Production Team C",
    progress: 0,
    estimatedHours: 24,
    actualHours: 0,
    createdAt: "2024-02-25T08:00:00Z",
    updatedAt: "2024-02-25T08:00:00Z",
    revision: "Rev A",
    notes: "Standard fabrication, minimal setup required",
  },
  {
    id: "WO4",
    workOrderNumber: "WO-2024-004",
    salesOrderId: "SO4",
    bomId: "",
    productName: "Bridge Girder Assembly",
    description: "Fabricate fracture critical bridge girders",
    quantity: 4,
    status: "Planned",
    priority: "Critical",
    startDate: "2024-03-15",
    dueDate: "2024-06-01",
    assignedTo: "Production Team A",
    progress: 0,
    estimatedHours: 320,
    actualHours: 0,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-01T10:00:00Z",
    revision: "Rev A",
    notes: "Major infrastructure project, requires special quality procedures",
  },
  {
    id: "WO5",
    workOrderNumber: "WO-2024-005",
    salesOrderId: "SO5",
    bomId: "",
    productName: "Solar Panel Mounting Structures",
    description: "Fabricate steel mounting frames and posts",
    quantity: 50,
    status: "Planned",
    priority: "Medium",
    startDate: "2024-03-20",
    dueDate: "2024-04-10",
    assignedTo: "Production Team B",
    progress: 0,
    estimatedHours: 80,
    actualHours: 0,
    createdAt: "2024-03-05T09:00:00Z",
    updatedAt: "2024-03-05T09:00:00Z",
    revision: "Rev A",
    notes: "Standard galvanized finish required",
  }
]

// Alias
export const productionWorkOrders = productionOrders

/* =========================
 *  BILLING
 * =======================*/

export const invoices: Invoice[] = [
  {
    id: "INV1",
    invoiceNumber: "INV-2024-001",
    customerId: "1",
    customerName: "Acme Construction Corp",
    salesOrderId: "SO1",
    status: "Sent",
    items: [
      { id: "INV1-I1", description: "W12x26 Steel I-Beam, 20ft length", quantity: 10, unitPrice: 450.0, totalPrice: 4500.0 },
      { id: "INV1-I2", description: "Custom connection plates", quantity: 20, unitPrice: 75.0, totalPrice: 1500.0 },
    ],
    subtotal: 6000.0,
    tax: 480.0,
    total: 6480.0,
    issueDate: "2024-02-20",
    dueDate: "2024-03-21",
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-02-20T10:00:00Z",
    revision: "Rev A",
    notes: "Payment due within 30 days",
  },
  {
    id: "INV2",
    invoiceNumber: "INV-2024-002",
    customerId: "2",
    customerName: "Metro Steel Works",
    salesOrderId: "SO2",
    status: "Draft",
    items: [
      { id: "INV2-I1", description: "W14x30 Steel Column, 12ft length", quantity: 8, unitPrice: 520.0, totalPrice: 4160.0 },
    ],
    subtotal: 4160.0,
    tax: 332.8,
    total: 4492.8,
    issueDate: "2024-02-25",
    dueDate: "2024-03-26",
    createdAt: "2024-02-25T09:00:00Z",
    updatedAt: "2024-02-25T09:00:00Z",
    revision: "Rev A",
    notes: "Auto-calculated tax at 8%",
  },
  {
    id: "INV3",
    invoiceNumber: "INV-2024-003",
    customerId: "3",
    customerName: "Blue Ridge Fabricators",
    salesOrderId: "SO3",
    status: "Sent",
    items: [
      { id: "INV3-I1", description: "Stair Stringer Assembly", quantity: 6, unitPrice: 300.0, totalPrice: 1800.0 },
      { id: "INV3-I2", description: "Mounting Brackets", quantity: 12, unitPrice: 30.0, totalPrice: 360.0 },
    ],
    subtotal: 2160.0,
    tax: 172.8,
    total: 2332.8,
    issueDate: "2024-03-01",
    dueDate: "2024-03-31",
    createdAt: "2024-03-01T11:00:00Z",
    updatedAt: "2024-03-01T11:00:00Z",
    revision: "Rev A",
    notes: "Net 30",
  },
  {
    id: "INV4",
    invoiceNumber: "INV-2024-004",
    customerId: "4",
    customerName: "Pacific Bridge & Steel",
    salesOrderId: "SO4",
    status: "Draft",
    items: [
      { id: "INV4-I1", description: "Plate Girder Assembly - 80ft span", quantity: 4, unitPrice: 8500.0, totalPrice: 34000.0 },
      { id: "INV4-I2", description: "Connection details and stiffeners", quantity: 16, unitPrice: 450.0, totalPrice: 7200.0 },
    ],
    subtotal: 41200.0,
    tax: 3296.0,
    total: 44496.0,
    issueDate: "2024-03-15",
    dueDate: "2024-05-14",
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-03-15T10:00:00Z",
    revision: "Rev A",
    notes: "Net 60 payment terms, major infrastructure project",
  },
  {
    id: "INV5",
    invoiceNumber: "INV-2024-005",
    customerId: "8",
    customerName: "California Solar Systems",
    salesOrderId: "SO5",
    status: "Draft",
    items: [
      { id: "INV5-I1", description: "Solar Panel Mounting Frame", quantity: 50, unitPrice: 120.0, totalPrice: 6000.0 },
      { id: "INV5-I2", description: "Ground Mounting Posts", quantity: 100, unitPrice: 45.0, totalPrice: 4500.0 },
    ],
    subtotal: 10500.0,
    tax: 840.0,
    total: 11340.0,
    issueDate: "2024-04-01",
    dueDate: "2024-05-01",
    createdAt: "2024-04-01T09:00:00Z",
    updatedAt: "2024-04-01T09:00:00Z",
    revision: "Rev A",
    notes: "Net 30, solar installation project",
  }
]

/* =========================
 *  PROCUREMENT
 * =======================*/

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "PO1",
    poNumber: "PO-2024-001",
    supplierId: "1", // Steel Supply Co
    supplierName: "Steel Supply Co",
    status: "Sent",
    priority: "Medium",
    items: [
      {
        id: "PO1-I1",
        partNumber: "STL-W12x26-20", // maps to BOM1-I1
        description: "W12x26 Steel Beam, 20ft raw",
        quantity: 12, // 10 for WO1 + 2 spare
        unit: "pieces",
        unitPrice: 380.0,
        totalPrice: 4560.0,
        steelGrade: "A992",
        urgency: "Medium",
        requestedDate: "2024-02-15",
        specifications: "ASTM A992 Grade 50",
        notes: "Include MTRs",
      },
    ],
    subtotal: 4560.0,
    tax: 364.8,
    total: 4924.8,
    orderDate: "2024-02-01",
    requestedDeliveryDate: "2024-02-15",
    paymentTerms: "Net 30",
    createdAt: "2024-02-01T11:00:00Z",
    updatedAt: "2024-02-01T11:00:00Z",
    revision: "Rev A",
    notes: "Rush order for production schedule",
  },
  {
    id: "PO2",
    poNumber: "PO-2024-002",
    supplierId: "2", // Welding Supply Inc
    supplierName: "Welding Supply Inc",
    status: "Acknowledged",
    priority: "Low",
    items: [
      {
        id: "PO2-I1",
        partNumber: "WLD-E70XX", // maps to BOM1-I2
        description: "E70XX Welding Rod",
        quantity: 50, // LB
        unit: "LB",
        unitPrice: 8.5,
        totalPrice: 425.0,
        steelGrade: "",
        urgency: "Low",
        requestedDate: "2024-02-10",
        specifications: "",
        notes: "Deliver to bay 2",
      },
    ],
    subtotal: 425.0,
    tax: 34.0,
    total: 459.0,
    orderDate: "2024-02-05",
    requestedDeliveryDate: "2024-02-10",
    paymentTerms: "Net 30",
    createdAt: "2024-02-05T09:00:00Z",
    updatedAt: "2024-02-06T09:00:00Z",
    revision: "Rev A",
    notes: "OK to partial",
  },
  {
    id: "PO3",
    poNumber: "PO-2024-003",
    supplierId: "3", // Precision Fasteners Ltd
    supplierName: "Precision Fasteners Ltd",
    status: "Sent",
    priority: "Medium",
    items: [
      {
        id: "PO3-I1",
        partNumber: "BOLT-A325-0.75x6",
        description: "Grade 8 Hex Bolt 3/4\"-13 x 6\"",
        quantity: 250,
        unit: "EA",
        unitPrice: 12.50,
        totalPrice: 3125.0,
        steelGrade: "A325",
        urgency: "Medium",
        requestedDate: "2024-03-01",
        specifications: "ASTM A325 Type 1, hex head with nut and washer",
        notes: "For bridge girder project",
      },
    ],
    subtotal: 3125.0,
    tax: 250.0,
    total: 3375.0,
    orderDate: "2024-02-20",
    requestedDeliveryDate: "2024-03-01",
    paymentTerms: "Net 30",
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-02-20T10:00:00Z",
    revision: "Rev A",
    notes: "High strength bolts for structural applications",
  },
  {
    id: "PO4",
    poNumber: "PO-2024-004",
    supplierId: "4", // Industrial Coatings Plus
    supplierName: "Industrial Coatings Plus",
    status: "Sent",
    priority: "Low",
    items: [
      {
        id: "PO4-I1",
        partNumber: "COAT-PRIMER-5GAL",
        description: "Industrial Primer - 5 gallon pail",
        quantity: 10,
        unit: "EA",
        unitPrice: 85.0,
        totalPrice: 850.0,
        steelGrade: "",
        urgency: "Low",
        requestedDate: "2024-03-15",
        specifications: "Zinc-rich primer for steel protection",
        notes: "For general steel fabrication",
      },
      {
        id: "PO4-I2",
        partNumber: "COAT-TOPCOAT-5GAL",
        description: "Industrial Topcoat - 5 gallon pail",
        quantity: 8,
        unit: "EA",
        unitPrice: 95.0,
        totalPrice: 760.0,
        steelGrade: "",
        urgency: "Low",
        requestedDate: "2024-03-15",
        specifications: "Alkyd enamel topcoat, various colors",
        notes: "For finished steel products",
      },
    ],
    subtotal: 1610.0,
    tax: 128.8,
    total: 1738.8,
    orderDate: "2024-02-25",
    requestedDeliveryDate: "2024-03-15",
    paymentTerms: "Net 30",
    createdAt: "2024-02-25T14:00:00Z",
    updatedAt: "2024-02-25T14:00:00Z",
    revision: "Rev A",
    notes: "Standard coating supplies for Q2",
  },
  {
    id: "PO5",
    poNumber: "PO-2024-005",
    supplierId: "5", // Quality Steel Processing
    supplierName: "Quality Steel Processing",
    status: "Draft",
    priority: "High",
    items: [
      {
        id: "PO5-I1",
        partNumber: "STL-PLATE-0.5x48x96",
        description: "Steel Plate 1/2\" x 48\" x 96\"",
        quantity: 25,
        unit: "EA",
        unitPrice: 180.0,
        totalPrice: 4500.0,
        steelGrade: "A36",
        urgency: "High",
        requestedDate: "2024-03-01",
        specifications: "ASTM A36 hot rolled steel plate",
        notes: "For connection plates and fabrication",
      },
    ],
    subtotal: 4500.0,
    tax: 360.0,
    total: 4860.0,
    orderDate: "2024-02-28",
    requestedDeliveryDate: "2024-03-01",
    paymentTerms: "Net 45",
    createdAt: "2024-02-28T11:00:00Z",
    updatedAt: "2024-02-28T11:00:00Z",
    revision: "Rev A",
    notes: "Rush order for production schedule",
  }
]

/* =========================
 *  UI HELPERS (unchanged)
 * =======================*/

export const statusColors = {
  quotation: {
    Draft: "bg-gray-100 text-gray-800",
    "Under Review": "bg-yellow-100 text-yellow-800",
    Sent: "bg-blue-100 text-blue-800",
    "Customer Review": "bg-purple-100 text-purple-800",
    Negotiation: "bg-orange-100 text-orange-800",
    Approved: "bg-green-100 text-green-800",
    Rejected: "bg-red-100 text-red-800",
    Expired: "bg-yellow-100 text-yellow-800",
  },
  salesOrder: {
    Draft: "bg-gray-100 text-gray-800",
    Confirmed: "bg-blue-100 text-blue-800",
    "In Production": "bg-yellow-100 text-yellow-800",
    Shipped: "bg-purple-100 text-purple-800",
    Delivered: "bg-green-100 text-green-800",
    Cancelled: "bg-red-100 text-red-800",
  },
  engineering: {
    Draft: "bg-gray-100 text-gray-800",
    "Under Review": "bg-yellow-100 text-yellow-800",
    Approved: "bg-green-100 text-green-800",
    Released: "bg-blue-100 text-blue-800",
    Obsolete: "bg-red-100 text-red-800",
  },
  bom: {
    Draft: "bg-gray-100 text-gray-800",
    "Under Review": "bg-yellow-100 text-yellow-800",
    Approved: "bg-green-100 text-green-800",
    Released: "bg-blue-100 text-blue-800",
    Obsolete: "bg-red-100 text-red-800",
  },
  production: {
    Planned: "bg-gray-100 text-gray-800",
    "In Progress": "bg-blue-100 text-blue-800",
    "On Hold": "bg-yellow-100 text-yellow-800",
    Completed: "bg-green-100 text-green-800",
    Cancelled: "bg-red-100 text-red-800",
  },
  invoice: {
    Draft: "bg-gray-100 text-gray-800",
    Sent: "bg-blue-100 text-blue-800",
    Paid: "bg-green-100 text-green-800",
    Overdue: "bg-red-100 text-red-800",
    Cancelled: "bg-gray-100 text-gray-800",
  },
  customer: {
    Active: "bg-green-100 text-green-800",
    Inactive: "bg-gray-100 text-gray-800",
    Suspended: "bg-red-100 text-red-800",
  },
  supplier: {
    Active: "bg-green-100 text-green-800",
    Inactive: "bg-gray-100 text-gray-800",
    Suspended: "bg-red-100 text-red-800",
  },
  purchaseOrder: {
    Draft: "bg-gray-100 text-gray-800",
    Sent: "bg-blue-100 text-blue-800",
    Acknowledged: "bg-yellow-100 text-yellow-800",
    Shipped: "bg-purple-100 text-purple-800",
    Received: "bg-green-100 text-green-800",
    Cancelled: "bg-red-100 text-red-800",
  },
}

export const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount)

export const formatDate = (dateString: string): string =>
  new Date(dateString).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })

/* =========================
 *  INVENTORY & LOCATIONS
 * =======================*/

export const items: Item[] = [
  {
    id: "1",
    partNumber: "STL-001",
    name: "Steel Plate 1/4\" x 48\" x 96\"",
    category: "Raw Material",
    description: "Hot rolled steel plate, A36 grade",
    unit: "EA",
    unitCost: 125.50,
    minStock: 10,
    maxStock: 100,
    currentStock: 45,
    leadTime: 14,
    supplier: "SteelCo Industries",
    location: "Warehouse A, Rack 3",
    status: "Active",
    specifications: "A36, Hot Rolled, 0.25\" thickness",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
    notes: "Primary steel stock for fabrication"
  },
  {
    id: "2",
    partNumber: "ALM-002",
    name: "Aluminum Bar 6061-T6",
    category: "Raw Material",
    description: "Extruded aluminum bar, 6061-T6 temper",
    unit: "FT",
    unitCost: 8.75,
    minStock: 50,
    maxStock: 500,
    currentStock: 125,
    leadTime: 7,
    supplier: "AlumCorp",
    location: "Warehouse B, Rack 1",
    status: "Active",
    specifications: "6061-T6, 1\" diameter, 12' length",
    createdAt: "2024-01-14T08:00:00Z",
    updatedAt: "2024-01-14T08:00:00Z",
    notes: "Used for non-ferrous applications"
  },
  {
    id: "3",
    partNumber: "BOLT-003",
    name: "Grade 8 Hex Bolt 1/2\"-13",
    category: "Fasteners",
    description: "High strength hex head bolt",
    unit: "EA",
    unitCost: 2.25,
    minStock: 100,
    maxStock: 1000,
    currentStock: 350,
    leadTime: 3,
    supplier: "FastenRight",
    location: "Warehouse C, Bin 7",
    status: "Active",
    specifications: "Grade 8, 1/2\"-13 thread, 2\" length",
    createdAt: "2024-01-13T08:00:00Z",
    updatedAt: "2024-01-13T08:00:00Z",
    notes: "Standard structural fastener"
  },
  {
    id: "4",
    partNumber: "WELD-004",
    name: "E7018 Welding Rod 1/8\"",
    category: "Consumables",
    description: "Low hydrogen welding electrode",
    unit: "LB",
    unitCost: 4.50,
    minStock: 25,
    maxStock: 200,
    currentStock: 75,
    leadTime: 5,
    supplier: "WeldSupply Co",
    location: "Warehouse A, Rack 5",
    status: "Active",
    specifications: "E7018, 1/8\" diameter, 14\" length",
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-12T08:00:00Z",
    notes: "Primary welding consumable"
  },
  {
    id: "5",
    partNumber: "FIN-005",
    name: "Steel Finishing Compound",
    category: "Finishing",
    description: "Chemical compound for steel surface treatment",
    unit: "GAL",
    unitCost: 45.00,
    minStock: 5,
    maxStock: 50,
    currentStock: 12,
    leadTime: 10,
    supplier: "ChemFinish Inc",
    location: "Warehouse B, Rack 8",
    status: "Active",
    specifications: "5 gallon pail, pH neutral",
    createdAt: "2024-01-11T08:00:00Z",
    updatedAt: "2024-01-11T08:00:00Z",
    notes: "Surface preparation chemical"
  },
  {
    id: "6",
    partNumber: "STL-006",
    name: "W12x26 Steel I-Beam",
    category: "Structural Steel",
    description: "ASTM A992 Grade 50 steel I-beam, 20ft length",
    unit: "EA",
    unitCost: 380.00,
    minStock: 2,
    maxStock: 20,
    currentStock: 8,
    leadTime: 14,
    supplier: "Steel Supply Co",
    location: "Warehouse A, Rack 4",
    status: "Active",
    specifications: "ASTM A992 Grade 50, W12x26 section, 20ft length",
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-02-15T16:00:00Z",
    notes: "Primary structural steel for building projects"
  },
  {
    id: "7",
    partNumber: "STL-007",
    name: "W14x30 Steel Column",
    category: "Structural Steel",
    description: "ASTM A992 Grade 50 steel column, 12ft length",
    unit: "EA",
    unitCost: 420.00,
    minStock: 1,
    maxStock: 15,
    currentStock: 5,
    leadTime: 21,
    supplier: "Metro Steel",
    location: "Warehouse A, Rack 4",
    status: "Active",
    specifications: "ASTM A992 Grade 50, W14x30 section, 12ft length",
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-02-12T09:00:00Z",
    notes: "For warehouse expansion project"
  },
  {
    id: "8",
    partNumber: "STL-008",
    name: "Steel Plate 1/2\" x 12\" x 20\"",
    category: "Steel Plate",
    description: "A36 steel plate for connection details",
    unit: "EA",
    unitCost: 150.00,
    minStock: 5,
    maxStock: 50,
    currentStock: 18,
    leadTime: 14,
    supplier: "Steel Supply Co",
    location: "Warehouse A, Rack 3",
    status: "Active",
    specifications: "ASTM A36, 1/2\" thick, 12\" x 20\" dimensions",
    createdAt: "2024-01-20T08:00:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
    notes: "For connection plates and fabrication"
  },
  {
    id: "9",
    partNumber: "WLD-009",
    name: "E70XX Welding Rod 3/32\"",
    category: "Consumables",
    description: "Low hydrogen welding electrode for structural steel",
    unit: "LB",
    unitCost: 5.25,
    minStock: 30,
    maxStock: 150,
    currentStock: 85,
    leadTime: 5,
    supplier: "Welding Supply Inc",
    location: "Warehouse A, Rack 5",
    status: "Active",
    specifications: "E70XX, 3/32\" diameter, 14\" length, AWS D1.1 compliant",
    createdAt: "2024-01-25T08:00:00Z",
    updatedAt: "2024-02-10T11:00:00Z",
    notes: "Primary welding consumable for structural steel"
  },
  {
    id: "10",
    partNumber: "BOLT-010",
    name: "Grade 8 Hex Bolt 3/4\"-13 x 6\"",
    category: "Fasteners",
    description: "High strength structural bolt with nut and washer",
    unit: "EA",
    unitCost: 12.50,
    minStock: 50,
    maxStock: 500,
    currentStock: 180,
    leadTime: 7,
    supplier: "Precision Fasteners Ltd",
    location: "Warehouse C, Bin 8",
    status: "Active",
    specifications: "ASTM A325 Type 1, 3/4\"-13 thread, 6\" length",
    createdAt: "2024-02-15T08:00:00Z",
    updatedAt: "2024-02-20T10:00:00Z",
    notes: "For bridge girder and structural connections"
    partNumber: "FG-006",
    name: "Custom Steel I-Beam Assembly",
    category: "Finished Goods",
    description: "Completed W12x26 I-beam with connection plates",
    unit: "EA",
    unitCost: 450.00,
    minStock: 2,
    maxStock: 20,
    currentStock: 8,
    leadTime: 0,
    supplier: "Internal Production",
    location: "Warehouse A, Finished Goods Bay",
    status: "Active",
    specifications: "ASTM A992 Grade 50, 20ft length, primed finish",
    createdAt: "2024-02-20T08:00:00Z",
    updatedAt: "2024-02-20T08:00:00Z",
    notes: "Ready-to-ship finished product from production"
  }
]

export const locations: Location[] = [
  {
    id: "1",
    code: "WH-A-01",
    name: "Warehouse A - Main Storage",
    type: "Warehouse",
    address: "123 Industrial Blvd, Manufacturing District",
    city: "Springfield",
    state: "IL",
    zipCode: "62701",
    country: "USA",
    contactPerson: "John Smith",
    phone: "+1-555-0123",
    email: "warehouse@company.com",
    capacity: 50000,
    currentUtilization: 75,
    temperature: "Ambient",
    humidity: "Standard",
    securityLevel: "High",
    status: "Active",
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
    items: 1250,
    value: 125000.00,
    notes: "Primary storage facility for raw materials and finished goods"
  },
  {
    id: "2",
    code: "WH-B-02",
    name: "Warehouse B - Cold Storage",
    type: "Warehouse",
    address: "456 Refrigeration Lane, Industrial Park",
    city: "Springfield",
    state: "IL",
    zipCode: "62702",
    country: "USA",
    contactPerson: "Sarah Johnson",
    phone: "+1-555-0456",
    email: "coldstorage@company.com",
    capacity: 25000,
    currentUtilization: 60,
    temperature: "2-8°C",
    humidity: "Low",
    securityLevel: "Medium",
    status: "Active",
    createdAt: "2024-01-14T08:00:00Z",
    updatedAt: "2024-01-14T08:00:00Z",
    items: 450,
    value: 75000.00,
    notes: "Temperature-controlled storage for sensitive materials"
  },
  {
    id: "3",
    code: "RACK-01",
    name: "Rack System 1",
    type: "Rack",
    address: "Warehouse A, Section 1",
    city: "Springfield",
    state: "IL",
    zipCode: "62701",
    country: "USA",
    contactPerson: "Mike Wilson",
    phone: "+1-555-0789",
    email: "racks@company.com",
    capacity: 5000,
    currentUtilization: 85,
    temperature: "Ambient",
    humidity: "Standard",
    securityLevel: "Medium",
    status: "Active",
    createdAt: "2024-01-13T08:00:00Z",
    updatedAt: "2024-01-13T08:00:00Z",
    items: 320,
    value: 45000.00,
    notes: "High-density storage for small parts and fasteners"
  },
  {
    id: "4",
    code: "BIN-01",
    name: "Small Parts Bin 1",
    type: "Bin",
    address: "Warehouse A, Rack 1, Level 2",
    city: "Springfield",
    state: "IL",
    zipCode: "62701",
    country: "USA",
    contactPerson: "Lisa Chen",
    phone: "+1-555-0321",
    email: "bins@company.com",
    capacity: 500,
    currentUtilization: 45,
    temperature: "Ambient",
    humidity: "Standard",
    securityLevel: "Low",
    status: "Active",
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-12T08:00:00Z",
    items: 225,
    value: 15000.00,
    notes: "Organized storage for small components and hardware"
  },
  {
    id: "5",
    code: "OFFICE-01",
    name: "Main Office Storage",
    type: "Office",
    address: "789 Corporate Plaza, Suite 100",
    city: "Springfield",
    state: "IL",
    zipCode: "62703",
    country: "USA",
    contactPerson: "David Brown",
    phone: "+1-555-0654",
    email: "office@company.com",
    capacity: 2000,
    currentUtilization: 30,
    temperature: "Climate Controlled",
    humidity: "Standard",
    securityLevel: "High",
    status: "Active",
    createdAt: "2024-01-11T08:00:00Z",
    updatedAt: "2024-01-11T08:00:00Z",
    items: 150,
    value: 25000.00,
    notes: "Secure storage for high-value items and documents"
  }
]
