import { ProcessStep } from "./types"

export interface ProcessStepTemplate {
  id: string
  name: string
  description: string
  category: string
  steps: ProcessStep[]
  isDefault: boolean
  createdAt: string
  updatedAt: string
  createdBy: string
}

export const getProcessStepTemplates = (): ProcessStepTemplate[] => {
  return [
    {
      id: "bus-duct-compact",
      name: "Compact Type Bus Duct Manufacturing",
      description: "Complete manufacturing process for compact bus duct systems with parallel conductor and shell processing",
      category: "Electrical Components",
      isDefault: false,
      createdBy: "Engineering Team",
      createdAt: "2024-03-20T08:00:00Z",
      updatedAt: "2024-03-20T08:00:00Z",
      steps: [
        // Conductor Processing Stage (Track A)
        {
          id: "BD-CP-001",
          workOrderId: "TEMPLATE",
          operationIndex: 0,
          stepName: "Conductor Straightening",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: false,
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 1,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-002",
          workOrderId: "TEMPLATE",
          operationIndex: 1,
          stepName: "Conductor Punching, Embossing",
          status: "Pending",
          estimatedDuration: 90,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 2,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-003",
          workOrderId: "TEMPLATE",
          operationIndex: 2,
          stepName: "Conductor Bending",
          status: "Pending",
          estimatedDuration: 75,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 3,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-004",
          workOrderId: "TEMPLATE",
          operationIndex: 3,
          stepName: "High-Temperature Baking",
          status: "Pending",
          estimatedDuration: 180,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: false,
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 4,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-005",
          workOrderId: "TEMPLATE",
          operationIndex: 4,
          stepName: "Conductor Insulation Layer Wrapping",
          status: "Pending",
          estimatedDuration: 120,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 5,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-006",
          workOrderId: "TEMPLATE",
          operationIndex: 5,
          stepName: "Conductor Surface Treatment",
          status: "Pending",
          estimatedDuration: 90,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: false,
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 6,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-007",
          workOrderId: "TEMPLATE",
          operationIndex: 6,
          stepName: "Insulation Pre-testing",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS9",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 7,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-CP-008",
          workOrderId: "TEMPLATE",
          operationIndex: 7,
          stepName: "Conductor Blanking",
          status: "Pending",
          estimatedDuration: 45,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS6",
          qualityCheckRequired: false,
          stage: "Conductor Processing",
          parallelTrack: "A",
          stageOrder: 8,
          dependsOn: [],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        // Shell Processing Stage (Track B)
        {
          id: "BD-SP-001",
          workOrderId: "TEMPLATE",
          operationIndex: 8,
          stepName: "Shell Raw Material Pretreatment",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: false,
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 1,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-SP-002",
          workOrderId: "TEMPLATE",
          operationIndex: 9,
          stepName: "Shell Raw Material Cutting",
          status: "Pending",
          estimatedDuration: 90,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 2,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-SP-003",
          workOrderId: "TEMPLATE",
          operationIndex: 10,
          stepName: "Bending / Forming",
          status: "Pending",
          estimatedDuration: 120,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 3,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-SP-004",
          workOrderId: "TEMPLATE",
          operationIndex: 11,
          stepName: "Welding / Riveting",
          status: "Pending",
          estimatedDuration: 150,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 4,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-SP-005",
          workOrderId: "TEMPLATE",
          operationIndex: 12,
          stepName: "Powder Coating",
          status: "Pending",
          estimatedDuration: 180,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 5,
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-SP-006",
          workOrderId: "TEMPLATE",
          operationIndex: 13,
          stepName: "Shell Blanking",
          status: "Pending",
          estimatedDuration: 45,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS7",
          qualityCheckRequired: false,
          stage: "Shell Processing",
          parallelTrack: "B",
          stageOrder: 6,
          dependsOn: [],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        // Product Assembly Stage (Track C - Converged)
        {
          id: "BD-PA-001",
          workOrderId: "TEMPLATE",
          operationIndex: 14,
          stepName: "Insulation Support Installation",
          status: "Pending",
          estimatedDuration: 90,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS8",
          qualityCheckRequired: false,
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 1,
          dependsOn: ["BD-CP-008", "BD-SP-006"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-002",
          workOrderId: "TEMPLATE",
          operationIndex: 15,
          stepName: "Conductor Assembly",
          status: "Pending",
          estimatedDuration: 120,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS8",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 2,
          dependsOn: ["BD-PA-001"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-003",
          workOrderId: "TEMPLATE",
          operationIndex: 16,
          stepName: "Housing Closure (Screw Tightening or Riveting)",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS8",
          qualityCheckRequired: false,
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 3,
          dependsOn: ["BD-PA-002"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-004",
          workOrderId: "TEMPLATE",
          operationIndex: 17,
          stepName: "Foreign Object Debris (FOD) Inspection",
          status: "Pending",
          estimatedDuration: 30,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS9",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 4,
          dependsOn: ["BD-PA-003"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-005",
          workOrderId: "TEMPLATE",
          operationIndex: 18,
          stepName: "Electrical Performance Testing",
          status: "Pending",
          estimatedDuration: 90,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS9",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 5,
          dependsOn: ["BD-PA-004"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-006",
          workOrderId: "TEMPLATE",
          operationIndex: 19,
          stepName: "Mechanical Performance Testing",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS9",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 6,
          dependsOn: ["BD-PA-005"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-007",
          workOrderId: "TEMPLATE",
          operationIndex: 20,
          stepName: "Sealing Performance Test",
          status: "Pending",
          estimatedDuration: 45,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS9",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 7,
          dependsOn: ["BD-PA-006"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-008",
          workOrderId: "TEMPLATE",
          operationIndex: 21,
          stepName: "PE Film Wrapping",
          status: "Pending",
          estimatedDuration: 30,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS5",
          qualityCheckRequired: false,
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 8,
          dependsOn: ["BD-PA-007"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        },
        {
          id: "BD-PA-009",
          workOrderId: "TEMPLATE",
          operationIndex: 22,
          stepName: "Package",
          status: "Pending",
          estimatedDuration: 30,
          actualDuration: 0,
          operatorId: "",
          workstationId: "WS5",
          qualityCheckRequired: false,
          stage: "Product Assembly",
          parallelTrack: "C",
          stageOrder: 9,
          dependsOn: ["BD-PA-008"],
          createdAt: "2024-03-20T08:00:00Z",
          updatedAt: "2024-03-20T08:00:00Z"
        }
      ]
    },
    {
      id: "T001",
      name: "Standard Steel Fabrication",
      description: "Basic steel cutting, welding, and finishing process",
      category: "Steel Fabrication",
      isDefault: true,
      createdBy: "System",
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T08:00:00Z",
      steps: [
        {
          id: "TS001",
          workOrderId: "TEMPLATE",
          operationIndex: 0,
          stepName: "Setup",
          status: "Pending",
          estimatedDuration: 120,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: false,
          createdAt: "2024-01-15T08:00:00Z",
          updatedAt: "2024-01-15T08:00:00Z"
        },
        {
          id: "TS002",
          workOrderId: "TEMPLATE",
          operationIndex: 1,
          stepName: "Cutting Operations",
          status: "Pending",
          estimatedDuration: 480,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          createdAt: "2024-01-15T08:00:00Z",
          updatedAt: "2024-01-15T08:00:00Z"
        },
        {
          id: "TS003",
          workOrderId: "TEMPLATE",
          operationIndex: 2,
          stepName: "Welding Operations",
          status: "Pending",
          estimatedDuration: 360,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          createdAt: "2024-01-15T08:00:00Z",
          updatedAt: "2024-01-15T08:00:00Z"
        },
        {
          id: "TS004",
          workOrderId: "TEMPLATE",
          operationIndex: 3,
          stepName: "Quality Check",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          createdAt: "2024-01-15T08:00:00Z",
          updatedAt: "2024-01-15T08:00:00Z"
        }
      ]
    },
    {
      id: "T002",
      name: "Rush Order Process",
      description: "Expedited process for urgent orders",
      category: "Rush Orders",
      isDefault: false,
      createdBy: "John Smith",
      createdAt: "2024-01-20T10:00:00Z",
      updatedAt: "2024-01-20T10:00:00Z",
      steps: [
        {
          id: "TR001",
          workOrderId: "TEMPLATE",
          operationIndex: 0,
          stepName: "Quick Setup",
          status: "Pending",
          estimatedDuration: 60,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: false,
          createdAt: "2024-01-20T10:00:00Z",
          updatedAt: "2024-01-20T10:00:00Z"
        },
        {
          id: "TR002",
          workOrderId: "TEMPLATE",
          operationIndex: 1,
          stepName: "Priority Cutting",
          status: "Pending",
          estimatedDuration: 240,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          createdAt: "2024-01-20T10:00:00Z",
          updatedAt: "2024-01-20T10:00:00Z"
        },
        {
          id: "TR003",
          workOrderId: "TEMPLATE",
          operationIndex: 2,
          stepName: "Fast Welding",
          status: "Pending",
          estimatedDuration: 180,
          actualDuration: 0,
          operatorId: "",
          workstationId: "",
          qualityCheckRequired: true,
          qualityStatus: "Pending",
          createdAt: "2024-01-20T10:00:00Z",
          updatedAt: "2024-01-20T10:00:00Z"
        }
      ]
    }
  ]
}
